# Generated by Django 4.2 on 2023-04-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientName', models.CharField(blank=True, max_length=100, null=True)),
                ('DateOfAppointment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
