# Generated by Django 4.2 on 2023-04-24 19:48

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_patients', '0001_initial'),
        ('manage_doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('authuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('DoctorID', models.CharField(default=uuid.uuid4, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('work_hours_start', models.TimeField(default=datetime.time(9, 0))),
                ('work_hours_end', models.TimeField(default=datetime.time(17, 0))),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
            bases=('manage_patients.authuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
