# Generated by Django 4.1.1 on 2023-04-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientName', models.CharField(blank=True, max_length=100, null=True)),
                ('DateOfAppointment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
