# Generated by Django 4.1.1 on 2023-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_doctors', '0004_alter_confirmappointment_dateofappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
