# Generated by Django 4.1.1 on 2023-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_doctors', '0005_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.CharField(blank=True, max_length=100, null=True)),
                ('fees', models.IntegerField(default=100)),
                ('deduction', models.IntegerField(default=0)),
                ('date_of_bill', models.DateTimeField(auto_now_add=True)),
                ('payable', models.IntegerField(default=100)),
            ],
        ),
    ]
